import logging as logger
from domain.models import ImageTag
from application.ports.image_analyzer import ImageAnalyzer
from azure.ai.vision.imageanalysis.models import VisualFeatures
from azure.ai.vision.imageanalysis.aio import ImageAnalysisClient


class VisionService(ImageAnalyzer):
    def __init__(self, client: ImageAnalysisClient): self.client = client

    async def generate_tags(self, image_url: str) -> list[ImageTag]:
        logger.info("Generating AI tags for image: %s", image_url)
        try:
            result = await self.client.analyze_from_url(image_url,[VisualFeatures.TAGS])
            if result.tags:
                logger.info("%a tags generated by VisionAI.", len(result.tags.list))
                return [ImageTag(tag.name, tag.confidence) for tag in result.tags.list]
            logger.warning("Azure Vision returned no caption for image URL %s", image_url)
            return []
        except Exception as e:
            logger.exception("Azure Vision analysis failed. Image: %s. Error: %a", image_url, e)
            raise

    async def generate_caption(self, image_url: str) -> str:
        try:
            result = await self.client.analyze_from_url(image_url,[VisualFeatures.CAPTION])
            if result.caption:
                logger.info("Generated caption: %s", result.caption.text)
                return result.caption.text
            logger.warning("No caption was generated. Should be investigated.")
            return str()
        except Exception as e:
            logger.exception("Azure Vision analysis failed. Image: %s. Error: %a", image_url, e)
            raise

    async def close_connection(self): 
        logger.debug("Closing Vision.AI Service connection...")
        await self.client.close()