<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Abstractions\Messaging\" />
    <Folder Include="Abstractions\Identity\" />
    <Folder Include="Posts\Commands\LikePost\" />
    <Folder Include="Posts\Commands\DislikePost\" />
    <Folder Include="Posts\Commands\NewFolder\" />
    <Folder Include="Posts\Commands\UnpublishPost\" />
    <Folder Include="Posts\Comments\Commands\AddComment\" />
    <Folder Include="Posts\Comments\Commands\EditComment\" />
    <Folder Include="Posts\Comments\Commands\DeleteComment\" />
    <Folder Include="Posts\Comments\Commands\ReportComment\" />
    <Folder Include="Posts\Commands\DeletePost\" />
    <Folder Include="Posts\Comments\Queries\GetLatestComments\" />
    <Folder Include="Posts\Comments\Queries\GetComments\" />
    <Folder Include="Posts\Galleries\Commands\SortGalleryItems\" />
    <Folder Include="Posts\Commands\PublishPost\" />
    <Folder Include="Posts\Galleries\Commands\UploadGalleryItem\" />
    <Folder Include="Posts\Galleries\Queries\GetGetGalleryById\" />
    <Folder Include="Posts\Galleries\Queries\GetPublicGalleries\" />
    <Folder Include="Posts\Galleries\Queries\GetUnpublished\" />
    <Folder Include="Interfaces\" />
    <Folder Include="Posts\Queries\GetPostById\" />
    <Folder Include="Posts\Queries\GetPublicPosts\" />
    <Folder Include="Posts\Queries\GetPrivatePostsByUserId\" />
    <Folder Include="Posts\Queries\NewFolder\" />
    <Folder Include="Reactions\Commands\" />
    <Folder Include="Reactions\Command\" />
    <Folder Include="Reactions\Queries\" />
    <Folder Include="Reactions\Queries\" />
    <Folder Include="Users\Commands\" />
    <Folder Include="Users\Queries\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Messaging.ServiceBus" Version="7.20.1" />
    <PackageReference Include="Azure.Storage.Blobs" Version="12.29.0" />
    <PackageReference Include="Mapster" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Features" Version="5.0.17" />
    <PackageReference Include="Newtonsoft.Json.Schema" Version="4.0.1" />
    <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CloudCanvas.Domain\CloudCanvas.Domain.csproj" />
  </ItemGroup>

</Project>
