
from typing import Protocol
from domain.models import ImageTag

class PersistenceService(Protocol): 
    def update_smartCaption(self, photo_id: str, ai_caption: str): ...
    def update_smartTags(self, photo_id: str, ai_tags: list[str]): ...
    def verify_no_prior_enrichment(self, photo_id: str) -> bool: ...
    def close_connection(self): ...