name: Build and Deploy ExtractMetadata Function
on: 
    push:
        branches:
            - main
        paths:
            - 'Functions/ExtractMetadata/**'
            - '.github/workflows/extract-metadata-deploy.yml'
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
            - name: 'Checkout Code'
              uses: actions/checkout@v4
            - name: 'Setup .NET'
              uses: actions/setup-dotnet@v4
              with: 
                dotnet-version: '8.0.x'
            - name: 'Cache or Download Nuget Packages'
              id: cache-nuget-packages
              uses: actions/cache@v4
              with:
                path: ~/.nuget/packages
                key: nuget-${{ runner.os }}-${{ hashFiles('**/*.csproj') }}
                restore-keys: |
                  nuget-${{ runner.os }}
                  nuget-
            - name: 'Check if NuGet Cache was restored'
              if: steps.cache-nuget-packages.outputs.cache-hit != 'true'
              run: echo "No cache hit — restoring packages from NuGet.org"
            - name: 'Restore Dependencies'
              run: dotnet restore Functions/ExtractMetadata/ExtractMetadata.csproj
            - name: 'Build'
              run: dotnet build Functions/ExtractMetadata/ExtractMetadata.csproj --configuration Release --no-restore
            - name: 'Publish'
              run: dotnet publish Functions/ExtractMetadata/ExtractMetadata.csproj --configuration Release --output ./publish
            - name: 'Deploy to Azure Fuctions App'
              uses: Azure/functions-action@v1
              with:
                app-name: ${{ secrets.APP_NAME_A }}
                publish-profile: ${{ secrets.PP_A }}
                package: ./publish